---
#프로덕션 환경
server:
  port: 2424
spring:
  config:
    import: classpath:application-auth.yml, classpath:application-mail.yml
    activate:
      on-profile: prod

---
#개발서버 환경
server:
  port: 2424
spring:
  config:
    import: classpath:application-auth.yml
    activate:
      on-profile: dev

---
#로컬 환경
server:
  port: 2424
spring:
  config:
    import: classpath:application-auth.yml
    activate:
      on-profile: local

---

