spring:
  config:
    import: classpath:application-oauth.yml
  profiles:
    default: local
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        globally_quoted_identifiers: true
cabinet:
  lent:
    term:
      private: 21
      share: 42
  penalty:
    day:
      share: 3
      padding: 2
overdue:
    term:
      soonoverdue: -1
      overdue: 1
