name: CI/CD
on:
  push:
    paths:
      - "backend/**"

jobs:
  backend-CI:
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb
        env:
          MARIADB_DATABASE: test_db
          MARIADB_USER: test_user
          MARIADB_PASSWORD: test_password
          MARIADB_ROOT_PASSWORD: test_password
        ports:
          - 3310:3306
        options: >-
          --health-cmd "mysqladmin ping -P 3306 -ptest_password | grep 'mysqld is alive' || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: 체크아웃
        uses: actions/checkout@v2
      - name: DB에 샘플 데이터 삽입
        run: >-
          mysql --force
          --host="127.0.0.1"
          --port="3310"
          --database="test_db"
          --user="test_user"
          --password="test_password"
          < "backend/src/test/resources/database/spring_test_db.sql"

      - name: JDK 11 설정
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: "amazon-corretto"

      - name: Gradle 빌드
        run: |
          cd backend
          chmod +x ./gradlew
          ./gradlew build
        shell: bash

  backend-CD-develop:
    name: deploy-develop
    runs-on: ubuntu-latest
    needs: [backend-CI]
    if: ${{ github.ref == 'refs/heads/dev' }}
    steps:
      - name: 리모트 쉘 접속
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DEV }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY_NEW }}
          port: ${{ secrets.PORT }}
          script_stop: true
          script: |
            source $HOME/.bash_profile
            echo "해당 리포지토리로 이동"
            cd $HOME/42cabi_dev
            echo "리포지토리 pull"
            git pull origin dev
            echo "앱 빌드"
            cd $HOME/42cabi_dev/backend
            npm install
            npm run build
            echo "env 파일 복사"
            cp $HOME/42cabi_dev.env $HOME/42cabi_dev/backend/.env
            echo "앱 배포 (reload)"
            pm2 reload cabi_dev

  backend-CD-main:
    name: deploy-main
    runs-on: ubuntu-latest
    needs: [backend-CI]
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: 리모트 쉘 접속
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_MAIN }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY_NEW }}
          port: ${{ secrets.PORT }}
          script_stop: true
          script: |
            source $HOME/.bash_profile
            echo "해당 리포지토리로 이동"
            cd $HOME/42cabi_main
            echo "리포지토리 pull"
            git pull origin main
            echo "앱 빌드"
            cd $HOME/42cabi_main/backend
            npm install
            npm run build
            echo "env 파일 복사"
            cp $HOME/42cabi_main.env $HOME/42cabi_main/backend/.env
            echo "앱 배포 (reload)"
            pm2 reload cabi_main
